import "./globals.css";
import { ReactNode } from "react";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { SessionProvider } from "@/contexts/session-provider-context";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html className={nunito.className} lang="en">
      <body className="bg-grayApp-800">
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
